version: 2.1

commands:
  install-awsebcli:
    description: install awsebcli
    steps:
      - run: git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
      - run: ./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: docker-compose up
          command: docker-compose up -d

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: aws
