version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16

jobs:
  build:
    machine: true
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run:
          name: docker-compose up
          command: docker-compose up -d

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: aws
