version: 2.1

orbs:
  awsebcli: sbc-orbs/awsebcli@0.0.3

jobs:
  build:
    machine: true
    steps:
      - checkout
      - awsebcli/install
      - awsebcli/configure
      - run:
          name: docker-compose up
          command: docker-compose up -d

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: aws
